config/routes.rb
Rails.application.routes.draw do

  devise_for :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root    "welcome#home", as: "home_page"

  # 7 deadly routes
  get "/companies"          =>     "companies#index", as: "companies"

  get "/signup"             =>     "companies#new", as: "new_company"
  post "/companies"         =>     "companies#create"

  get "/companies/:id"      =>     "companies#show", as: "company"
  get "/companies/edit" =>     "companies#edit", as: "edit_company"
  put "/companies/:id"      =>     "companies#update"
  patch  "/companies/:id"   =>     "companies#update"
  delete "/companies/:id"   =>     "companies#destroy"

  resources :jobs
  resources :boats






end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord

  belongs_to :company
  has_and_belongs_to_many :jobs


  has_attached_file :avatar,
    :styles => { :medium => "300x300px>", :thumb => "100x100px>" },
    :default_url => "http://www.golenbock.com/wp-content/uploads/2015/01/placeholder-user.png"

  validates_attachment_content_type :avatar,
    :content_type => /\Aimage\/.*\Z/

end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :boats
  has_many :jobs, :through => :boats


  has_attached_file :avatar,
    :styles => { :medium => "300x300px>", :thumb => "100x100px>" },
    :default_url => "http://www.golenbock.com/wp-content/uploads/2015/01/placeholder-user.png"

  validates_attachment_content_type :avatar,
    :content_type => /\Aimage\/.*\Z/


  # validates_uniqueness_of :name
  validates :name , uniqueness: {case_sesitive: false}

end

app/models/job.rb
class Job < ApplicationRecord

  has_and_belongs_to_many :boats

  validates :name , uniqueness: {case_sesitive: false}

  validates :cost, :numericality => { :greater_than => 1000 }

  validates_length_of :description, :minimum => 50

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :name, :address])
  end


  def  after_sign_in_path_for(resource)
    company_path(resource.id)
  end

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController

    def index
      @all_boats = Boat.all
      @boat = Boat.new
    end

    def new
      @boat = Boat.new
    end

    def create
      @new_boat = Boat.create(
      name: params[:boat][:name],
      containers: params[:boat][:containers],
      location: params[:boat][:location],
      company_id: params[:boat][:company_id],
      avatar: params[:boat][:avatar]
      )
      #
      if @new_boat
        redirect_to url_for(:controller => :boats, :action => :index)
      else
        redirect_to url_for(:controller => :boats, :action => :new)
      end
#################################
      # # respond_to invisible/present on every controller action
      # respond_to do |format|
      #   # If request is JS (AJAX)
      #   format.js
      #
      #   # If request is normal Rails way
      #   format.html { redirect_to boats_path }
      # end
    end

    def show
      @boat = Boat.find(params[:id])
      # @job = Job.find(params[:id])
      @boat_company = @boat.company.email
    end

    def edit
      @message = "This is the form to edit an existing boat."
      @boat = Boat.find(params[:id])
    end

    def update
      @boat = Boat.find(params[:id])
      @boat.update({
        name: params[:boat][:name],
        containers: params[:boat][:containers],
        location: params[:boat][:location],
        company_id: params[:boat][:company_id],
        avatar: params[:boat][:avatar]
        })

      if (@boat)
        redirect_to url_for(:controller => :boats, :action => :index)
      else
        redirect_to url_for(:controller => :boats, :action => :edit)
      end
    end

    def destroy
      Boat.delete(params[:id])
      redirect_to url_for(:controller => :boats, :action => :index)
    end



end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @all_companies = Company.all
    @company_new = Company.new
  end

  def new
    @message = "New Company"
  end

  def create
    puts params[:company]

    @company = Company.create(
    name: params[:company][:name],
    address: params[:company][:address]
    )

    # respond_to invisible/present on every controller action
    respond_to do |format|
      # If request is JS (AJAX)
      format.js

      # If request is normal Rails way
      format.html { redirect_to companies_path }
    end

  end



  before_action :authenticate_company!
  def show
    @company = Company.find(params[:id])
    # company has many boats
    @company_boats = @company.boats
    @boat = Boat.new
  end


  def edit
    # @message = "This is the form to edit an existing company."
    # @company = Company.find(params[:id])
  end



  def update
    @company = Company.find(params[:id])
    @company.update({
      name: params[:company][:name],
      address: params[:company][:address]
      })

    if (@company)
      redirect_to url_for(:controller => :companies, :action => :index)
    else
      redirect_to url_for(:controller => :companies, :action => :edit)
    end
  end



  def destroy
    Company.delete(params[:id])
    redirect_to url_for(:controller => :companies, :action => :index)
  end




end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @all_jobs = Job.all
    @job = Job.new
  end

  def new
    @job = Job.new
    @boats_arr = Boat.all
  end

  def create
    @new_job = Job.create(
    name: params[:job][:name],
    description: params[:job][:description],
    origin: params[:job][:origin],
    destination: params[:job][:destination],
    cost: params[:job][:cost],
    amount_containers: params[:job][:amount_containers]
    )
    # @new_job.boats << Boat.find(params[:boats_jobs][:boat_id])

    params[:boat][:boat_ids].each do |boat_id|
      @id = boat_id.to_i
      @new_job.boats << Boat.find(@id)
    end


    if @new_job
      redirect_to url_for(:controller => :jobs, :action => :index)
    else
      redirect_to url_for(:controller => :jobs, :action => :new)
    end

    # # respond_to invisible/present on every controller action
    # respond_to do |format|
    #   # If request is JS (AJAX)
    #   format.js
    #
    #   # If request is normal Rails way
    #   format.html { redirect_to jobs_path }
    # end

  end


  def show
    # @all_jobs = Job.all
    @job = Job.find(params[:id])
    @boats_assigned = @job.boats
    @boats = Boat.all
  end


  def edit
    @message = "This is the form to edit an existing job."
    @job = Job.find(params[:id])
    @boats_arr = Boat.all
  end

  def update
    @job = Job.find(params[:id])
    @job.update({
      name: params[:job][:name],
      description: params[:job][:description],
      origin: params[:job][:origin],
      destination: params[:job][:destination],
      cost: params[:job][:cost],
      amount_containers: params[:job][:amount_containers]
      })

      @job.boats.clear
      params[:job][:boat_ids].each do |boat_id|
        @job.boats << Boat.find(boat_id.to_i)
      end


    if (@job)
      redirect_to url_for(:controller => :jobs, :action => :index)
    else
      redirect_to url_for(:controller => :jobs, :action => :edit)
    end
  end

  def destroy
    Job.delete(params[:id])
    redirect_to url_for(:controller => :jobs, :action => :show)
  end



  # def add_boat
  #   @job = Job.find(params[:id])
  #   @boat = Boat.find(params[:id])
  #
  #   @job.boats.push(@boat)
  # end
  #
  #
  # def remove_boat
  #   @job = Job.find(params[:id])
  #   @boat = Boat.find(params[:id])
  #
  #   @job.boats.delete(@boat)
  # end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    @message = "Welcome to ShippMate Shipping App"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boats/create.js.erb
$("#boats-list").append("<li><%= @boat.id %>. <%= @boat.name %></li>")

app/views/boats/edit.html.erb
<h1>Edit boat</h1>

<%= form_for @boat do |f| %>
  <%= f.label :name %>:<br>
  <%= f.text_field :name %> <br><br>

  <%= f.label :containers %>:<br>
  <%= f.text_field :containers %> <br><br>

  <%= f.label "current location" %><br>
  <%= f.select :location, ["Bermuda", "India", "Miami", "New York City", "Panama", "Trinidad", "Hong Kong", "Thailand", "London", "Australia", "Fiji"], prompt: :select %><br><br>

  <%= f.label :company %>: <br>
  <%= f.collection_select :company_id, Company.all, :id, :name %>

  <br><br>
  <center><%= f.file_field :avatar %><br>

  <%= f.submit %>
<% end %>

app/views/boats/index.html.erb
<h1>List of All Boats</h1>

<div class="links">
  <h4><%= link_to ("Create New Boat"), new_boat_path %></h4>
</div>
<hr>

<h4><% @all_boats.each do |boat| %>
  <%= boat.id %>.
  Boat Name: <%= boat.name %> <br>
  Number of Containers: <%= boat.containers %> <br>
  Location: <%= boat.location %><br><br>

  <%= image_tag boat.avatar.url%>

  <br>
<div class="links">
  ||<%= link_to ("Boat show page"), boat_path(boat.id) %>
  ||<%= link_to ("Boat edit page"), edit_boat_path(boat.id) %>
  ||<%= link_to 'Delete boat',  { action: :destroy, id: boat.id }, method: :delete %>||
</div>

<hr>

<% end %>
</h4>

app/views/boats/new.html.erb
<h1>new page for boats</h1>

<%= form_for Boat.new do |f| %>
  <%= f.label "Name of boat" %>:
  <%= f.text_field :name %><br><br>

  <%= f.label "Number of Containers" %>:
  <%= f.text_field :containers %><br><br>

  <%= f.label "current location" %>
  <%= f.select :location, ["Bermuda", "India", "Miami", "New York City", "Panama", "Trinidad", "Hong Kong", "Thailand", "London", "Australia", "Fiji"], prompt: :select %><br><br>

  <%= f.label :company %>
  <%= f.collection_select :company_id, Company.all, :id, :email %><br><br>

<center><%= f.file_field :avatar %>
  <br>

  <%= f.submit "Submit New Boat"%>
<% end %>

app/views/boats/show.html.erb
<h1><%= @boat.company.name %>'s Boats</h1>


  <p><b>Boat Name:</b> <%= @boat.name %></p>
	<p><b># of Containers:</b> <%= @boat.containers %></p>
	<p><b>Location:</b> <%= @boat.location %></p>
	<p><b>Boat Owner:</b> <%= @boat.company.name %></p>

<div class="links">
  <%= image_tag @boat.avatar.url(:thumb) %>
  <% if @boat.company == current_company %>
		<%= link_to "Edit Boat", edit_boat_path(@boat) %>
		<%= link_to "Delete Boat", @boat, method: :delete %>
	<% end %>
</div>

<hr>

app/views/companies/index.html.erb
<h1>List of All Companies</h1>


<h4><% @all_companies.each do |company| %>
  <%= company.id %>.
  Company Name: <%= company.name %>,<br>
  Address: <%= company.address %><br>
  Email: <%= company.email %><br>
  Member Since: <%= company.created_at.strftime(" %B %d, %Y")%>

  <br><br>

<div class="links">
  ||<%= link_to ("Company show page"), company_path(company.id) %>
  ||<%= link_to 'Delete company',  { action: :destroy, id: company.id }, method: :delete %>||
  <hr><br>
</div>

<% end %></h4>

app/views/companies/show.html.erb
	<h3><div class="links">
		<div class="pull-left">
			<%= link_to "[ Edit My Account ]", edit_company_path(@company) %>
		</div>

		<div class="pull-right">
		<%= link_to "[ Create Boat ]", new_boat_path %> <br>
		</div>
	</div></h3>
<hr>



<h1><%= @company.name %>'s Profile</h1>

<h4><% @company.id %>
Company Name: <%= @company.name %><br>
Address: <%= @company.address %><br>
Email: <%= @company.email %><br>
Member Since: <%= @company.created_at.strftime(" %B %d, %Y")%>
</h4>

<br>

<div class="company-photo">
	<%= image_tag @company.avatar.url(:thumb) %>
</div>

<hr>


<h4><div>Boats Needed by <%= @company.name %>:</div></h4>


	<% @company.boats.each do |boat| %>
		<p><b>Boat Name:</b> <%= boat.name %></p>
		<p><b># of Containers:</b> <%= boat.containers %></p>
		<p><b>Current Location:</b> <%= boat.location %></p>
		<p><b>Boat Owner:</b> <%= boat.company.name %></p>



		<div class="boat-photo">
			<%= image_tag boat.avatar.url(:thumb) %>
		</div>

		<br>

		<div class="links">
				<%= link_to "Show Details", boat_path(boat) %>
		<!-- User can only edit / delete boats on their own profile page -->
			<% if @company == current_company %>
				<%= link_to "Edit Boat", edit_boat_path(boat) %>
				<%= link_to "Delete Boat", boat, method: :delete %>
		</div>

<hr>

		<% end %>
	<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Your Current Jobs</h1>

<%= form_for @job do |f| %>

  <%= f.label :name %>:
  <%= f.text_field :name %> <br><br>

  <%= f.label :description %>
  <%= f.text_field :description %> <br><br>


  <%= f.label "Origin location" %>:
  <%= f.select :origin, ["Bermuda", "India", "Miami", "New York City", "Panama", "Trinidad", "Hong Kong", "Thailand", "London", "Australia", "Fiji"], prompt: :select %><br><br>

  <%= f.label "Destination location" %>:
  <%= f.select :destination, ["Bermuda", "India", "Miami", "New York City", "Panama", "Trinidad", "Hong Kong", "Thailand", "London", "Australia", "Fiji"], prompt: :select %><br><br>

  <%= f.label "Cost: $" %>
  <%= f.text_field :cost %> <br><br>

  <%= f.label :amount_containers %>:
  <%= f.select :amount_containers, (1..100), prompt: :select %> <br><br>

  <!-- <%= f.label :boat %>:
  <%= collection_select :boats_jobs, :boat_id, Boat.all, :id, :name %><br><br> -->


  <% @boats_arr.each do |boat| %>
    <%= check_box_tag "boat[boat_ids][]", boat.id %>
    <%= f.label boat.name %>
    <br>
  <% end %>


  <%= f.submit %>
<% end %>

app/views/jobs/index.html.erb
<h1>List of All Jobs</h1>

<div class="links">
  <h3><%= link_to ("Create a New Job for Boat"), new_job_path %></h3>
</div>

<h4><% @all_jobs.each do |job| %>


Job Name: <%= job.name %> <br>
Description: <%= job.description %> <br><br>
Origin: <%= job.origin %> <br>
Destination: <%= job.destination %> <br><br>
Cost: <%= job.cost %> <br>
Containers Needed: <%= job.amount_containers %>

<div class="links">
||<%= link_to ("Job Details"),job_path(job.id) %>
||<%= link_to ("Edit Job"), edit_job_path(job.id) %>
||<%= link_to 'Delete Job',  { action: :destroy, id: job.id }, method: :delete %>||
</div>
<hr>

<% end %></h4>

app/views/jobs/new.html.erb
<h1>Add A New Job</h1>


<%= form_for Job.new do |f| %>

  <%= f.label "Name of Job" %>:
  <%= f.text_field :name %> <br><br>

  <%= f.label :description %>:
  <%= f.text_field :description %> <br><br>


  <%= f.label "Origin location" %>:
  <%= f.select :origin, ["Bermuda", "India", "Miami", "New York City", "Panama", "Trinidad", "Hong Kong", "Thailand", "London", "Australia", "Fiji"], prompt: :select %><br><br>

  <%= f.label "Destination location" %>:
  <%= f.select :destination, ["Bermuda", "India", "Miami", "New York City", "Panama", "Trinidad", "Hong Kong", "Thailand", "London", "Australia", "Fiji"], prompt: :select %><br><br>

  <%= f.label "Cost: $" %>
  <%= f.text_field :cost %> <br><br>

  <%= f.label "Amount of containers" %>:
  <%= f.select :amount_containers, (1..100), prompt: :select %> <br><br>

  <!-- <%= f.label "Boat Name" %>:
  <%= collection_select :boats_jobs, :boat_id, Boat.all, :id, :name %><br><br> -->


  <p><b>Select Boats For This Job:</b></p>
  <% @boats_arr.each do |boat| %>
    <%= check_box_tag "boat[boat_ids][]", boat.id %>
    <%= f.label boat.name %>
    <br>
  <% end %>




<br>

  <%= f.submit %>
<% end %>

app/views/jobs/show.html.erb
<h1>JOB INFO</h1>
<h4>
Job Name: <%= @job.name %><br>
Description: <%= @job.description%><br>
Origin: <%= @job.origin%><br>
Destination: <%= @job.destination%><br>
Cost: $<%= @job.cost%><br>
Containers Needed: <%= @job.amount_containers%><br>
</h4>

<hr>

<h3>All Boats Assigned To This Job:</h3>

<% @boat_job_ids = [] %>

<h4><% @job.boats.each do |boat| %>
 <% @boat_job_ids << boat.id %><br>
Boat Name: <%= boat.name %><br>
Location: <%= boat.location%><br><br>
<%= image_tag boat.avatar.url%>

<br>

<div class="links">
||<%= link_to ("boat show page"), boat_path(boat.id) %>
||<%= link_to ("boat edit page"), edit_boat_path(boat.id) %>
||<%= link_to 'Delete boat',  { action: :destroy, id: boat.id }, method: :delete %>||
</div>
<% end %>
</h4>


<hr>
<h3>All Boats Not Assigned To This Job:</h3>

<% @all_boat_ids = [] %>

<% @boats.each do |boat| %>
  <% @all_boat_ids << boat.id %>
<% end %><br>


<% @final_arr = @all_boat_ids - @boat_job_ids %>

<% @final_arr.each do |t|%>
  Boat Name: <%= Boat.find(t).name %><br>
  Containers: <%= Boat.find(t).containers %><br>
  Location: <%= Boat.find(t).location %><br><br>
<% end %>






<!-- -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShippedProject</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Quicksand|Raleway|Rubik" rel="stylesheet">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <nav class="navbar">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand logo" href="/">ShippMate</a>
          </div>

          <!-- <div class="links pull-left">
            |<a href="/companies">Companies</a>|
            <a href="/boats">Boats</a>|
            <a href="/jobs">Jobs</a>|
          </div> -->

        <div class="links pull-left">
          |<%= link_to ("Companies"), companies_path %>|
          <%= link_to ("Boats"), boats_path %>|
          <%= link_to ("Jobs"), jobs_path %>|
        </div>


        <div class="links pull-right">
        <% if  (company_signed_in?)%>
              <%= link_to "Sign out", { :action => "destroy",  :controller=> "devise/sessions"}, method: :delete %>
        <% else %>
              <%= link_to "Sign In", new_company_session_path %>
              <%= link_to "Sign Up", new_company_registration_path %>
        <% end %>
      </div>
      </div>
    </nav>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="info">

    <%= yield %>

    </div>




  </body>
</html>

app/views/welcome/home.html.erb
<h1><%= @message %></h1>

<div class="homey">

<p>ShippMate.com is a website you can trust for shipping quotes from companies that have high quality service at a lower price. Shipping large quantities of goods or bulky products can be overwhelming and expensive but with us by your side, we can lessen the stress without breaking your bank account. If you trust us to assist you with your shipping needs, you can rest assured that there will never be a big problem that can’t be solved.</p>

<p>The biggest advantage of getting a shipping quote is the power to choose the best shipping provider with a reasonable or even low price. By getting a quote, you are making it possible to save as much as 35% in the shipping cost simply by comparing and making a smart choice. But you not only get this benefit by getting a shipping quote from us, you will also be entitled with the following:

<ul>
<li>Get a free shipping coordination service when you sign up with us. Our competent shipping coordinators will help make the shipping process as smooth as possible with their expertise in the field</li>

<li>Get better customer service all the time as we make sure that we only partner with reputable and leading companies to handle your needs</li>

<li>Get instant quote access in just one place- no need to fill out several forms over and over again. This way you get convenience and save time in getting a shipping quote
Get access to more than 2,500 shipping companies and professional haulers</li>

<li>Get the power to customize your shipping needs and avoid unnecessary charges, hidden fees and service charges
Get full protection for your valuables with the insurance that comes with the shipping service.</li>
</ul>

<p>We know that each of customer’s need is unique that’s why we made sure that we give you the power to customize your shipping needs. Whether you need a full service move and shipping service that includes the packing, boxing and delivery of your goods or whether you require door to door service or even a service as simple as port to port shipping only, we can definitely assist and address your needs.</p>

</div>